config/routes.rb
Rails.application.routes.draw do
  resources :myclasses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/myclass.rb
class Myclass < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/myclasses_controller.rb
class MyclassesController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @myclasses = Myclass.all
  end

  def show
    @myclass = Myclass.find(params[:id])
  end

  def new
  end

  def create
    Myclass.create(:name=>params[:name])
    redirect_to myclasses_path
  end

  def edit
  end

  def update
    myclass = Myclass.find(params[:id])
    myclass.update(name:params[:name])
    redirect_to myclasses_path
  end

  def destroy
    myclass = Myclass.find(params[:id])
    myclass.delete
    redirect_to myclasses_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classsystem1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/myclasses/edit.html.erb
<h1>修改班级</h1>
<form action='/myclasses/<%=params[:id]%>' method=POST>
  <input type='hidden' name='_method' value='put'>
  班级名称:<input type='text' name='name'><br>
  <input type='submit' value='提交'>
</form>

app/views/myclasses/index.html.erb
Myclass#index

<table>
  <tr>
    <td>班级ID</td>
    <td>班级名称</td>
  </tr>
  <% @myclasses.each do |myclass| %>
    <tr>
      <td><%= myclass.id %></td>
      <td><%= myclass.name %></td>
      <td><%= link_to '查看班级', myclass %></td>
      <td><%= link_to '修改班级', edit_myclass_path(myclass) %></td>
      <td><%= link_to '删除班级', myclass, method: :delete %></td>      

    </tr>
  <% end %>
    <tr>
      <td><%= link_to '添加班级', new_myclass_path %></td>
    </tr>
</table>

app/views/myclasses/new.html.erb
#new<br>
添加班级<br>
<form action='/myclasses' method=POST>
  班级名称:<input type='text' name='name'><br>
  <input type='submit' value='提交'>
</form>

app/views/myclasses/show.html.erb
Myclass#show

<table>
  <tr>
    <td>班级名称</td>
  </tr>

</table>